apiVersion: compute.cnrm.cloud.google.com/v1alpha1
kind: ComputeFirewall
metadata:
  labels:
    label-one: "value-one"
  name: computefirewall-sample
spec:
  allow:
    - protocol: tcp
    - protocol: icmp
  networkRef:
    name: computenetwork-sample
