apiVersion: compute.cnrm.cloud.google.com/v1alpha1
kind: ComputeFirewall
metadata:
  labels:
    label-one: "value-one"
  name: computefirewall-allow-sample
spec:
  allow:
    - protocol: tcp
      ports:
       - "80"
       - "1000-2000"
  networkRef:
    name: computefirewall-dep
