apiVersion: compute.cnrm.cloud.google.com/v1alpha1
kind: ComputeFirewall
metadata:
  labels:
    label-one: "value-one"
  name: computefirewall-deny-sample
spec:
  deny:
    - protocol: icmp
  networkRef:
    name: computefirewall-dep
